### ISSUE TITLE
Launch

### ISSUE THREAD

**Issue by ecrus** [neowutran/ShinraMeter#128]
Hi, I've completed all the prereq for the DPS meter program, but when I get in game no info shows up after attacking monsters. Is there something I'm missing? I went through the guide about 8 times and followed all the steps.

**Comment by Gl0** [comment]
Are you using latest version? Not sure what guide you are mentioning, but there are only 2 needed steps to make latest version working - either install winpcap/npcap (this way might not work with some network configurations), either create incoming firewall rule and use raw sockets mode (if winpcacp/npcap is not installed - it will be used automatically, otherwise need to change config). Setting details - https://github.com/neowutran/ShinraMeter/wiki#network 
If you are using some proxy/vpn solution - only raw sockets mode would work + you'll need to adjust servers.txt for it.
btw, @neowutran, may be add servers-override.txt to config dir like it done in casual to prevent proxy settings from loosing on update?

**Comment by ecrus** [comment]
Yep! It's the latest version and I had a firewall rule setup as well as winpcap/npcap installed.

**Comment by Gl0** [comment]
try raw sockets

> Edit window.xml to switch  <winpcap>false</winpcap>

**Comment by hsluoyz** [comment]
Hi @ecrus ,

I have solved a similar issue in Npcap today. Please try latest Npcap 0.07 R8 at: https://github.com/nmap/npcap/releases
