### ISSUE TITLE
Dps Meter showing as black box in stream

### ISSUE THREAD

**Issue by TepaSarcy** [neowutran/ShinraMeter#141]
Hey

I have problem on dps meter showing as black box while trying to stream, i'm using obs and i put it as window on scene and did make the transparency false from the window file as told to, tried to check some of the boxes but nothing seemed to work.

So is there something else that i need to do than just make it false to make it work? Anyone else had a problem with that?

Thank you.

**Comment by Gl0** [comment]
AFAIK OBS doesn't support detection of wpf window resize. So you can make it visible, but capture region will be the same as it was at the time it was configured. Until OBS maintainers add wpf window resize detection the only workaround is to use desktop capture.

**Comment by TepaSarcy** [comment]
Ah i see =/ Thanks.

**Comment by Alukar** [comment]
Just need to disable transparency and set opacity = 100. In that case everything will work. Win aero disabling doesn't required.

**Comment by Gl0** [comment]
window resize following works too?

**Comment by Alukar** [comment]
Yes, window resize works for me.

**Comment by Gl0** [comment]
Rechecked - latest version of OBS Studio capture main window well with just <allow_transparency>false</allow_transparency>, no need to change opacity settings since they are not working with transparency disabled. Strange, that there is no comment about it in patch notes. Or may be that's not OBS change, but my "backup" ATI video card instead of NVIDIA one, on which I've tested capture before.

**Comment by Gl0** [comment]
Received new nvidia card from CU - same old problem with window resize tracking appeared again.
So OBS can't track meter window size on nvidia cards...

**Comment by Gl0** [comment]
Ups. Rechecked - with obs **studio** all is working even on nvidia card.
Occasionally started old plain obs yesterday.
