### ISSUE TITLE
The meter breaks after checking damage breakdown

### ISSUE THREAD

**Issue by ha-tam** [neowutran/ShinraMeter#15]
After boss1 -> check skill. Start boss2 -> Meter stays on boss1, no dps updates. boss2 dps isn't listed

**Comment by Gl0** [comment]
Now it falls to deadlock during the battle while switching between boss and adds.
When I choose break all in debugger, it shows lock (Lock) in EntitiesDealt.LastHit {get}

**Comment by neowutran** [comment]
yeah, thanks, I m on it, I think that will be fixed tonight/tomorrow

**Comment by neowutran** [comment]
I had two "idea" to fix that: 
- First idea:  Check every read / write operation and add lock / ReaderWriterLockSlim
- Second idea: Having only 2 thread.
 The first thread read the network and do all the writing operation, and send a copy of the data to the UI thread 
The UI thread just read the data & display what we want.  
So no need to lock anything, only need to implement a clone method.

 I m going for the second idea since it seem easier and I won't have to deal with any dead lock nor waiting time between lock/unlock. 


Any opinion about that?

**Comment by neowutran** [comment]
Seem to be fixed now
