### ISSUE TITLE
Cant get it to work with MudFish Vpn(ping reducer)

### ISSUE THREAD

**Issue by Azuyz** [neowutran/ShinraMeter#235]
I have it running on raw sockets added every IP in the resource manager tied to Tera in the override*
Still wont work

As I'm getting into game the char select when it says Fey forest for a second
Then swaps to some Korean(ithink?) text i cant read it
http://puu.sh/siPZp/c6ec80e022.png (the text)
Worked fine with wtfast on raw sockets and normal

**Comment by flowzeph** [comment]
Having the same issue, DPS Meter doesn't work with MudFish on raw sockets either.

**Comment by Gl0** [comment]
show me your server-overrides.txt

**Comment by Azuyz** [comment]
[server-overrides.txt](https://github.com/neowutran/ShinraMeter/files/592113/server-overrides.txt)

**Comment by Gl0** [comment]
Installed mudfish and looked what's happening:
mudfish seems working over plain openvpn, so it should work even via npcap but it constantly pinging KR server over TCP, I have no idea, why - this seems to be a mudfish bug, and you need to ask mudfish support, why their client is trying to connect to KR Tera server even if you are playing NA Tera.
Each new connection attempt make meter to forget currently tracked connection and try to detect new keys. As a workaround you can delete KR strings from servers.txt, so that connection to KR Tera wouldn't be tracked by meter at all.
Also you can delete server-overrides.txt, no need for anything you've added.

**Comment by Azuyz** [comment]
Cheers a lot that did fix the issue Ty and i will ask support about it
Thanks again and for the work on the meter
