### ISSUE TITLE
Autoupdate seem to don't work in russia / taiwan

### ISSUE THREAD

**Issue by neowutran** [neowutran/ShinraMeter#27]
Probably an encoding problem when I read the online file that contains the version number

**Comment by neowutran** [comment]
Should be fixed now, with version 0.61

**Comment by Gl0** [comment]
Seems issue is still exist, here is error.log from ru forum:
`2016-02-05 15:26:30,466 ERROR DamageMeter.AutoUpdate.Program - ##### UPDATE EXCEPTION (version=0.61): #####
An error occurred while sending the request.
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.AutoUpdate.UpdateManager.<GetResponseText>d__16.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в DamageMeter.AutoUpdate.UpdateManager.<GetResponseText>d__16.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.AutoUpdate.UpdateManager.<GetResponseText>d__16.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.AutoUpdate.UpdateManager.<GetResponseText>d__16.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.AutoUpdate.UpdateManager.<GetResponseText>d__16.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.AutoUpdate.UpdateManager.<GetResponseText>d__15.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.AutoUpdate.UpdateManager.<LatestVersion>d__12.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.AutoUpdate.UpdateManager.<IsUpToDate>d__6.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.UI.App.<CheckUpdate>d__4.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.UI.App.<App_OnStartup>d__2.MoveNext()
mscorlib
System.Net.Http.HttpRequestException: An error occurred while sending the request. —> System.Net.WebException: Базовое соединение закрыто: Непредвиденная ошибка при передаче. —> System.IO.IOException: Аутентификация не пройдена из-за закрытия транспортного потока удаленной стороной.
 в System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
 в System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
 в System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
 — Конец трассировки внутреннего стека исключений —
 в System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
 в System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
 — Конец трассировки внутреннего стека исключений —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.AutoUpdate.UpdateManager.<GetResponseText>d__16.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в DamageMeter.AutoUpdate.UpdateManager.<GetResponseText>d__16.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.AutoUpdate.UpdateManager.<GetResponseText>d__16.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.AutoUpdate.UpdateManager.<GetResponseText>d__16.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.AutoUpdate.UpdateManager.<GetResponseText>d__16.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.AutoUpdate.UpdateManager.<GetResponseText>d__15.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.AutoUpdate.UpdateManager.<LatestVersion>d__12.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.AutoUpdate.UpdateManager.<IsUpToDate>d__6.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.UI.App.<CheckUpdate>d__4.MoveNext()
— Конец трассировка стека из предыдущего расположения, где возникло исключение —
 в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 в DamageMeter.UI.App.<App_OnStartup>d__2.MoveNext()
System.Collections.ListDictionaryInternal
System.Net.WebException: Базовое соединение закрыто: Непредвиденная ошибка при передаче. —> System.IO.IOException: Аутентификация не пройдена из-за закрытия транспортного потока удаленной стороной.
 в System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
 в System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
 в System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
 — Конец трассировки внутреннего стека исключений —
 в System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
 в System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
Void ThrowForNonSuccess(System.Threading.Tasks.Task)`
Russian error text translates to something like "authentication failure due to transport stream termination by remote side".

**Comment by neowutran** [comment]
ok, thanks x). I'm gonna have a hard time trying to debug something I'm not able to reproduce. 
Maybe some kind of ssl issues, but don't know

**Comment by neowutran** [comment]
I will try to add that:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3;
(source: http://www.avivroth.com/2013/05/02/rest-calls-in-net-c-over-ssl-https/ )

**Comment by neowutran** [comment]
The auto update system can't work for XP and Vista. 
That can only work with Windows 7, 8 and 10

(TLS 1.2)

**Comment by neowutran** [comment]
If some ppl still have pb with auto update & they use window 7, 8 or 10, reopen this issue

**Comment by Gl0** [comment]
There is no dotnet 4.6 for xp =)
