### ISSUE TITLE
PC blocks while running a dungeon with ShinraMeter running

### ISSUE THREAD

**Issue by Syphiria** [neowutran/ShinraMeter#299]
Hello. Yesterday I downloaded ShinraMeter. I ran LKNM and my screen blocked while the first boss. I couldn't do anything but turn off the PC with the power button. Same thing happened at the last boss. Then I ran a dungeon without ShinraMeter on and it didn't block. I tried it yesterday and it's still the same. When I run ShinraMeter my PC blocks instantly.
Any solution?

**Comment by Gl0** [comment]
May be something wrong with video or audio drivers. Try to mute sound or disable notification and chat services in settings menu.

**Comment by Syphiria** [comment]
Yesterday I added it to the firewall exception, muted sounds and disabled notification and chat services. After that it didn't crash anymore, but today my PC crashed again. 
Error file is empty.
I disabled the display scaling on high DPI settings in Tera properties.

![disable](https://cloud.githubusercontent.com/assets/25722837/22904288/2b850998-f23c-11e6-835d-d08c75f95863.jpg)

**Comment by Gl0** [comment]
DPI settings can't affect this.
Anything in windows event log? But if PC just freeze - there probably will be nothing too.
May be some hardware issue with memory/video or incompatibility with pcap. Try switching to raw sockets to be sure that issue is not pcap related.
Or even overheat problem. Have you checked your system for stability (both cpu/memory and video)?

**Comment by Syphiria** [comment]
My PC doesn't have overheating problems. 
I just tried the 1.77 version instead of 1.78 and it seems to work!
Thanks anyway.

**Comment by Gl0** [comment]
The only difference between 1.77 and 1.78 is latest KR DB. +Some new updater code that was disabled before publishing.
