### ISSUE TITLE
[Request] boss HP indication/calculation in notifications

### ISSUE THREAD

**Issue by ve3k** [neowutran/ShinraMeter#314]
Hello.

Is it possible to setup/adjust events to include boss HP% during the event and/or some basic calculations on this HP?
example:
Boss enraged <HP%>
Boss enraged ended, next natural enrage <(HP% - 20%)>

Also I would like to know if its possible to post notifications like these in party chat.

Cheers,

**Comment by Gl0** [comment]
Post notifications in party chat can't be done without injecting chat packets. Meter is passive by design, and can't inject anything.
Due to this limitation it's useless to include HP% in notification, you see it ingame at the same moment, and can't see it later.
We have plans to add floating window with at least next enrage/enrage time left indicator, but don't have time to implement it properly.

**Comment by ve3k** [comment]
Thanks for the info, cant wait for the enrage indicator :)

**Comment by neowutran** [comment]
https://github.com/neowutran/ShinraMeter/issues/317
