### ISSUE TITLE
Meter wont start.

### ISSUE THREAD

**Issue by HotValk** [neowutran/ShinraMeter#318]
Hey,
I installed everything like in guide, and when i 1st time run the meter it crashed and made blue screen (fatal error), and than after pc reset it just doesnt do anything. no icon in tray, nothing when i try to start meter.

I tried editing window.xml, i tried with and without npcap.
I tried also another dps meter and it has exacly same issues, so the problem isnt on the program side but in somethin else, but i have no idea in what. 

Can some1 help figuring it out?

**Comment by Gl0** [comment]
bsod may be caused by npcap, need to check minidump for details (use something like http://www.nirsoft.net/utils/blue_screen_view.html ). If it is npcap issue, please report it to npcap team with all logs they need to find the root of the problem.
Tray icon may be [hidden](https://www.howtogeek.com/wp-content/uploads/2016/10/img_580ab50544559.png).
