### ISSUE TITLE
Stops working in dungeons

### ISSUE THREAD

**Issue by myshya89** [neowutran/ShinraMeter#423]
Hello,
I'm playing in Windowed Full Screen, added exception to Firewall, set a high priority to the process. Still, Shinra stops working whenever I enter any dungeon, at max when the first boss is down. It doesn't generate any error, it just disappears. Everywhere outside dungs it works normally.

**Comment by neowutran** [comment]
For this kind of thing, faster to ask on discord 

But if it "disappear" will running: 
- It can have been silently killed by some antivirus or things like that
- It still running properly, but doesn't show up on top of tera because of a GPU driver bug

Also check the common things: 
Game is in windowed mode?
error.log contains something? 
Antivirus ( or things like this ) killed it ?
