### ISSUE TITLE
Can I rewrite the code of your windows?

### ISSUE THREAD

**Issue by ko-kin** [neowutran/ShinraMeter#492]
Can I rewrite the code of your windows so that they can be handled through the MVVM pattern?

At the moment I have to climb and look for methods in which I can make a Direct3D 11 overlay injector, this is very inconvenient ...

I can rewrite your windows so that you can work with them by separating the business logic from the design.

**Comment by Gl0** [comment]
take a look at https://github.com/neowutran/ShinraMeter/tree/mvvm_refactor_wip

**Comment by ko-kin** [comment]
Okay, as I understand it, no one has done this yet, right?
Can I commit to this branch after refactoring is complete?

And yet, I will use the Prism library, will it not interfere in any way?

**Comment by Gl0** [comment]
it's in beta stage, and this branch is already used for toolbox-integrated version release.

**Comment by SaltyMonkey** [comment]
Why would you include prism in already working code without it? And who will maintain custom library after your commit? :)

**Comment by ko-kin** [comment]
Well, okay, just awful written code, it is impossible to figure out what and where to write an in-game overlay library.

**Comment by Gl0** [comment]
https://github.com/neowutran/ShinraMeter/blob/mvvm_refactor_wip/DamageMeter.UI/Windows/MainViewModel.cs
doesn't look complicated.

**Comment by SaltyMonkey** [comment]
Huh.
1) If you are trying to contribute in opensource then you shouldn't blindy shittalk another ppl's work
2) It is common sense to discuss big changes with contributers and users through issues tab - your ideas, for sure, can be rejected by current owner/contributers and nothing bad in dat situation
3) It is common sense to keep codestyle of original project - you are not only one here
4) Long life projects will have some historical "questionable things" and there, for sure, reasons - even if you believe something is wrong...
5) Codebase can be "bad" or "broken" but these terms completely subjective based on point of view - maybe you are just not expierenced enough
6) Just because you like something it is doesnt force everyone to have same opinion - in your case its Prism which is completely unnecessary when everything already done without it

**Comment by ko-kin** [comment]
The thing is that with Prism, it would be possible to load the overlay module only when the user actually wants it, i.e. the library would not be loaded into memory until the user decides that he needs an overlay in the game.

**Comment by Gl0** [comment]
Not sure why you need prizm for that...
Switching to prizm may be not a bad idea overall, but doubt you can do it properly if "it is impossible to figure out what and where to write an in-game overlay library." for you.

**Comment by ko-kin** [comment]
Okay, then I'll just write a client / server renderer, and you can decide how and when to send messages to the renderer for data updates, rendering and so on.
