### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by EscobarTony** [neowutran/ShinraMeter#75]
Just thought I would let you know that with the most recent version of Npcap the DRIVER_IRQL_NOT_LESS_OR_EQUAL BSoD still happens. I would like to know more info about it because all i know is that it has something to do with the packet capture library. Thank you and keep up the good work.

**Comment by neowutran** [comment]
Npcap is used as the default method to capture packet. 
I have pretty much no knowledge about possible bug in npcap. Maybe you can try here: 
https://github.com/nmap/npcap#contact

What you can try: 
Desactivate every antivirus + 
Desactivate every firewall (window firewall etc) +
Use raw socket 

Also, try to update your networking hardware drivers if their is any upgrade available
Make all windows update

What are the technical detail about your networking hardware? Wireless card model, ethernet card model etc
And what OS? and, ultimate, basic, familial, professional version of window? 

Your computer is definitly weird, I don't have any clue on what is going on on your computer

**Comment by hsluoyz** [comment]
Hi,

I'm working on Npcap's ``DRIVER_IRQL_NOT_LESS_OR_EQUAL`` BSoD these days. And it is supposed to have been fixed in the latest Npcap 0.06 R13. So please try the latest installer at: https://github.com/nmap/npcap/releases.

If you still encounter the same BSoD, let me know your Npcap version and provide me the dump file (located in ``C:\Windows\Minidump``). Thanks!

Cheers,
Yang
