### ISSUE TITLE
dps calculation

### ISSUE THREAD

**Issue by woortoo** [neowutran/ShinraMeter#85]
Should dps formula be reworked to total_damage/timer? Now damage dealer can afk half the encounter and get same dps as others or mystic can use thrall and get 2mil/s. This number will be add to party dps and we will see incredible nonsense dps. More party dps must be equal faster kill but now it is not.

**Comment by neowutran** [comment]
Lack of documentation, but party dps is "TotalDamage / FightDuration" .
So my choose of personnal DPS doesn't modify party dps. 

Also, put your mouse over the individual dps & you will see a tooltip with the dps you expected to see

I put both dps because they both seems interesting to me.
But lack of doc & lack of configuration possibility

**Comment by woortoo** [comment]
Sorry then, but yesterday i saw 4mil/s party with 2mil/s mystic at teradps.io and thought it is because shinra. I shall contact them instead.

**Comment by neowutran** [comment]
I just checked what I send to teradps.io, I send the individual dps instead of the dps you expected to see. I will correct that with the next release. 

But the partyDps that I send seems correct 

If you found strange result on teradps.io, please send a link here, or here: https://github.com/kiritsuzu/teraDPS-API . We can check what is wrong

 (Keep in mind that everything about teradps.io is still very young, so probably still many problem to find)

**Comment by Gl0** [comment]
Yesterday there can be such numbers due to -80%CDR event on RU servers.
